Example Terraform Code Optimization
terraform-ibm-modules/terraform-ibm-kms-key pull request #557
Opened 2024-03-19 08:51 UTC by marifse

### Description

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-03-19 08:52 UTC, marifse commented
@ocofaigh please check this PR, i have created after addressing the previous concerns. And if ok then please approve. Thanks

2024-03-19 10:07 UTC, ocofaigh commented
/run pipeline

2024-03-19 10:17 UTC, ocofaigh requested changes
the var name is wrong in cra-config.yaml

2024-03-19 10:17 UTC, ocofaigh commented on cra-config.yaml
> +      TF_VAR_regions: "us-south"
typo. should be `TF_VAR_region`

2024-03-19 10:46 UTC, marifse commented
> the var name is wrong in cra-config.yaml

fixed.

2024-03-19 11:12 UTC, ocofaigh submitted a review, later dismissed

2024-03-19 11:12 UTC, ocofaigh commented
/run pipeline

2024-03-19 11:40 UTC, marifse commented
@ocofaigh the variable value for prefix not found for unit test, whereas the value is already being passed as "options := setupOptions(t, "kms-key")".

2024-03-19 12:09 UTC, ocofaigh commented
@marifse Since the test is using `TestOptionsDefault` (instead of `TestOptionsDefaultWithVars`) it means you need to explicitly pass any required variables to the test. So since region and prefix are now required, can you update the test to this:

```
func TestRunBasicExample(t *testing.T) {
	t.Parallel()

        options := testhelper.TestOptionsDefault(&testhelper.TestOptions{
		Testing:      t,
		TerraformDir: basicExampleTerraformDir,
		Prefix:       "kms-key-basic",
	})

        terraformVars := map[string]interface{}{
		"prefix": options.Prefix,
		"region":   options.Region,
		"existing_kms_instance_guid":   permanentResources["hpcs_south"],
	}

	options.TerraformVars = terraformVars

	output, err := options.RunTestConsistency()
	assert.Nil(t, err, "This should not have errored")
	assert.NotNil(t, output, "Expected some output")
}
```

2024-03-19 12:15 UTC, marifse commented
@ocofaigh also for complete example test or only for this basic one?

2024-03-19 12:18 UTC, ocofaigh commented
@marifse No the complete example is using `TestOptionsDefaultWithVars` which will always pass a value for prefix and region

2024-03-19 12:33 UTC, ocofaigh commented
/run pipeline

2024-03-19 12:52 UTC, marifse commented
> /run pipeline

please re-run pipeline, i have added the region value in basic example test

2024-03-19 12:56 UTC, ocofaigh commented
/run pipeline

2024-03-19 13:22 UTC, ocofaigh commented on tests/pr_test.go
> +		"region":                     options.Region,
actually the basic example doesnt have a region input var, so please remove this

2024-03-19 13:22 UTC, ocofaigh commented on tests/pr_test.go
> +		Region:       "us-south",
same as https://github.com/terraform-ibm-modules/terraform-ibm-kms-key/pull/557/files#r1530357875

2024-03-19 14:23 UTC, ocofaigh commented
/run pipeline

2024-03-19 14:24 UTC, marifse commented
@ocofaigh region removed, please run the pipeline now.

2024-03-19 15:00 UTC, ocofaigh approved these changes

2024-03-19 15:01 UTC, merged

2024-06-11 08:37 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.2.4 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-kms-key/releases/tag/v1.2.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: